#include "AmicableNumbers.hpp"
#include "CountingSundays.hpp"
#include "EvenFibonacci.hpp"
#include "FactorialDigitSum.hpp"
#include "HighlyDivisibleTriangularNumber.hpp"
#include "LargestPalindromeProduct.hpp"
#include "LargestPrimeFactor.hpp"
#include "LargestProductInAGrid.hpp"
#include "LargestProductInASeries.hpp"
#include "LargeSum.hpp"
#include "LatticePath.hpp"
#include "LexicographicPermutation.hpp"
#include "LongestCollatzSequence.hpp"
#include "MaximumPathSum1.hpp"
#include "MultiplesOfThreeAndFive.hpp"
#include "NamesScore.hpp"
#include "NonAbundantSums.hpp"
#include "NumberLetterCounts.hpp"
#include "NumbersToWords.hpp"
#include "PowerDigitSum.hpp"
#include "PythagoreanTriplet.hpp"
#include "ReciprocalCycles.hpp"
#include "SmallestMultiple.hpp"
#include "SquareSumDifference.hpp"
#include "SummationOfPrimes.hpp"
#include "TenThousandFirstPrime.hpp"
#include "ThousandDigitFibonacciNumber.hpp"

int main()
{
//  AmicableNumbers();
//  CountingSundays();
//  NamesScore();
//  EvenFibonacci();
//  FactorialDigitSum();
//  HighlyDivisibleTriangularNumber();
//  LargestPalindromeProduct();
//  LargestPrimeFactor();
//  LargestProductInAGrid();
//  LargestProductInASeries();
//  LargeSum();
//  LatticePath();
  LexicographicPermutation();
//  LongestCollatzSequence();
//  MaximumPathSum1();
//  MultiplesOfThreeAndFive();
//  NonAbundantSums();
//  NumberLetterCounts();
//  NumbersToWords();
//  PowerDigitSum();
//  PythagoreanTriplet();
//  ReciprocalCycles();
//  SmallestMultiple();
//  SquareSumDifference();
//  SummationOfPrimes();
//  TenThousandFirstPrime();
//  ThousandDigitFibonacciNumber();

  return 0;
}
