#include "AmicableNumbers.hpp"
#include "CoinSums.hpp"
#include "CountingSundays.hpp"
#include "DigitFifthPowers.hpp"
#include "DistinctPowers.hpp"
#include "EvenFibonacci.hpp"
#include "FactorialDigitSum.hpp"
#include "HighlyDivisibleTriangularNumber.hpp"
#include "LargestPalindromeProduct.hpp"
#include "LargestPrimeFactor.hpp"
#include "LargestProductInAGrid.hpp"
#include "LargestProductInASeries.hpp"
#include "LargeSum.hpp"
#include "LatticePath.hpp"
#include "LexicographicPermutation.hpp"
#include "LongestCollatzSequence.hpp"
#include "MaximumPathSum1.hpp"
#include "MultiplesOfThreeAndFive.hpp"
#include "NamesScore.hpp"
#include "NonAbundantSums.hpp"
#include "NumberLetterCounts.hpp"
#include "NumberSpiralDiagonals.hpp"
#include "NumbersToWords.hpp"
#include "PandigitalProducts.hpp"
#include "PowerDigitSum.hpp"
#include "PythagoreanTriplet.hpp"
#include "QuadraticPrimes.hpp"
#include "ReciprocalCycles.hpp"
#include "SmallestMultiple.hpp"
#include "SquareSumDifference.hpp"
#include "SummationOfPrimes.hpp"
#include "TenThousandFirstPrime.hpp"
#include "ThousandDigitFibonacciNumber.hpp"

int main()
{
//  AmicableNumbers();
//  CoinSums();
//  CountingSundays();
//  DigitFifthPowers();
//  DistinctPowers();
//  EvenFibonacci();
//  FactorialDigitSum();
//  HighlyDivisibleTriangularNumber();
//  LargestPalindromeProduct();
//  LargestPrimeFactor();
//  LargestProductInAGrid();
//  LargestProductInASeries();
//  LargeSum();
//  LatticePath();
//  LexicographicPermutation();
//  LongestCollatzSequence();
//  MaximumPathSum1();
//  MultiplesOfThreeAndFive();
//  NamesScore();
//  NonAbundantSums();
//  NumberLetterCounts();
//  NumberSpiralDiagonals();
//  NumbersToWords();
  PandigitalProducts();
//  PowerDigitSum();
//  PythagoreanTriplet();
//  QuadraticPrimes();
//  ReciprocalCycles();
//  SmallestMultiple();
//  SquareSumDifference();
//  SummationOfPrimes();
//  TenThousandFirstPrime();
//  ThousandDigitFibonacciNumber();

  return 0;
}
